version: 2

# Circle jobs
jobs:
  # Publish the image set to S3
  publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: git config --global user.email "origami.support@ft.com";
      - run: git config --global user.name "origamiserviceuser [bot]";
      - run: npm ci
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run: npm version --git-tag-version=false ${CIRCLE_TAG} -m "%s" && git push origin HEAD:master
      - run: npm publish --access=public

# Circle workflows
workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
