name: Publish to npm and s3
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.3
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: git config --global user.email "origami.support@ft.com";
    - run: git config --global user.name "origamiserviceuser [bot]";
    - run: npm ci
    - name: Get the version
      id: version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - run: npm version --no-git-tag-version ${{ steps.version.outputs.VERSION }}
    - run: git push origin HEAD:master
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
